// custom_event.js
// ===============
//
// Created at 2010/05/07
// Copyright (c) 2010-2012 Wolfger Schramm <wolfger@spearwolf.de>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
(function(){function x(b,c,a,f){var g=u++,b={name:b,eType:c,node:a};c===p&&(b.callback=f.callback);r[g]=b;return g}function j(b,c){this.eType=y;this.name=b;this.parentNode=c;this.children=[];this.greedyChildren=[];this.insatiableChildren=[];this.callbacks=[]}function s(b,c,a){var a=a||{},f=null;if("string"===typeof b)return a.name=b,f=m.findOrCreateNode(b).addCallback(c,a),{eType:v,id:f.id,name:f.name,destroy:function(){d.destroy(f.id);delete this.eType;delete this.id;delete this.name;delete this.destroy;
delete this.emit;delete this.pause},emit:function(){d.emit.apply(i,[f.name].concat(Array.prototype.slice.call(arguments)))},pause:function(a){return"boolean"===typeof a?f.paused=a:f.paused}};if("function"===typeof b&&b.eType===t)return b.on(c)}function w(b,c){var a=[],f=[],g,e,n,o=b,h=c;(n="object"===typeof o)?"function"===typeof o.collect&&(g=o.collect):(h=b,o={});for(e=n?2:1,n=arguments.length;e<n;++e)!0===o.collect&&e===n-1&&"function"===typeof arguments[e]?g=arguments[e]:a.push(arguments[e]);
l.traceGroup("_e.emit ->",h);var j;"object"!==typeof d._emitStackTrace?d._emitStackTrace={currentLevel:1,topicPath:[]}:++d._emitStackTrace.currentLevel;j=d._emitStackTrace;m.matchNodes(h,function(b,c){try{var g=[],o=function(a){return function(){g.push(a)}},n,i,k,m;for(e=0;e<b.callbacks.length;e++)k=b.callbacks[e],k.paused?l.trace("_e.on -> (paused)",k.name,"["+k.id+"]",k):0>j.topicPath.indexOf(k.id)?(j.topicPath.push(k.id),i=k.binding||{},i.name=h,i.destroy=o(k.id),"undefined"===typeof i.eType&&
(i.eType=v),m=a,"undefined"!==typeof c&&(i.pathArgs=c.split(d.options.pathSeparator),m=i.pathArgs.concat(a)),l.trace("_e.on ->",k.name,"["+k.id+"]",k,"args=",m),n=k.fn.apply(i,m),k.once&&g.push(k.id),null!==n&&"undefined"!==typeof n&&f.push(n),j.topicPath.pop()):l.error("_e.on -> (skipped/recursion)",k.name,"["+k.id+"]",k);b.destroyCallbacks(g)}catch(p){l.error(p)}});--d._emitStackTrace.currentLevel;0===d._emitStackTrace.currentLevel&&(d._emitStackTrace={currentLevel:0,topicPath:[]});g&&0<f.length&&
g.apply(i,f);l.traceGroupEnd()}function q(b,c){var a,c=c||m;if("number"===typeof b)if(a=r[b]){if(a.eType===p){var f=a.node.eValueFunction.listener,g=a.callback,e;for(e=0;e<f.length;e++)if(f[e]===g){f.splice(e,1);break}l.debug("destroy --\>",a);return!0}delete r[b]}else{if(0<c.destroyCallbacks([b]))return!0;for(a=0;a<c.children.length;a++)if(q(b,c.children[a]))return!0;for(a=0;a<c.greedyChildren.length;a++)if(q(b,c.greedyChildren[a]))return!0;for(a=0;a<c.insatiableChildren.length;a++)if(q(b,c.insatiableChildren[a]))return!0}return!1}
var i=this,d={VERSION:"0.7.0-pre2"};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=d),exports._e=d):"function"===typeof define&&define.amd?(define("custom_event",function(){return d}),define("custom_event/global",function(){return i._e=d})):i._e=d;var l=function(){var b="undefined"!==typeof i.console&&"function"===typeof Function&&"function"===typeof Function.prototype.bind,c=b&&"function"===typeof i.console.group,a={},f=!b?void 0:function(a){return Function.prototype.bind.call(console[a],
console)},g=b?f("error"):null,e=b?f("log"):null,n=b?f("log"):null,o=c?f("group"):null,h="";b?(a.error=function(){g.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},a.debug=function(){d.options.debug&&e.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},a.trace=function(){d.options.trace&&n.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},c?(a.debugGroup=function(){d.options.debug&&o.apply(console,
[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},a.debugGroupEnd=function(){d.options.debug&&console.groupEnd()},a.traceGroup=function(){d.options.trace&&o.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},a.traceGroupEnd=function(){d.options.trace&&console.groupEnd()}):(a.debugGroup=function(){d.options.debug&&(e.apply(i,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments))),h+="    ")},a.traceGroup=function(){d.options.trace&&
(n.apply(i,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments))),h+="    ")},a.traceGroupEnd=a.debugGroupEnd=function(){h=h.substr(0,h.length-4)})):a.error=a.debug=a.trace=a.traceGroup=a.traceGroupEnd=function(){};return a}(),y="EventNode",t="ValueFunction",p="ValueChangeListener",v="EventListener",u=1,r={},m=new j;j.prototype.fullPathName=function(){return"undefined"===typeof this.name?d.options.pathSeparator:this._fullPathName()};j.prototype._fullPathName=function(){return"undefined"===
typeof this.name?"":this.parentNode._fullPathName()+d.options.pathSeparator+this.name};j.prototype.addChild=function(b){var c=new j(b,this);b===d.options.greedyChar?this.greedyChildren.push(c):b===d.options.insatiableSequence?this.insatiableChildren.push(c):this.children.push(c);return c};j.prototype.splitPath=function(b){for(var b=b.split(d.options.pathSeparator),c=null;null===c||0===c.length;)c=b.shift();if(c===d.options.insatiableSequence)return[c,""];for(var a=[],f=0;f<b.length&&!(a.push(b[f]),
b[f]===d.options.insatiableSequence);f++);return[c,0===a.length?"":a.join(d.options.pathSeparator)]};j.prototype.matchNodes=function(b,c){var a=this.splitPath(b),f=a[0],a=a[1],g=this,e;for(e=0;e<g.insatiableChildren.length;e++)c(g.insatiableChildren[e],b);if(0<a.length){for(e=0;e<this.children.length;e++)g=this.children[e],(f===d.options.greedyChar||f===g.name)&&g.matchNodes(a,c);for(e=0;e<this.greedyChildren.length;e++)this.greedyChildren[e].matchNodes(a,c)}else{for(e=0;e<this.children.length;e++)g=
this.children[e],(f===d.options.greedyChar||f===g.name)&&c(g);for(e=0;e<this.greedyChildren.length;e++)c(this.greedyChildren[e])}};j.prototype.findOrCreateNode=function(b,c){var a=this.splitPath(b),f=a[0],a=a[1],c="undefined"===typeof c?!0:c,g=function(a){return function(b){var f,g;for(f=0;f<a.children.length;f++)if(g=a.children[f],b===g.name)return g;if(c)for(f=0;f<a.greedyChildren.length;f++)if(g=a.greedyChildren[f],b===g.name)return g;return null}}(this)(f);null===g&&(g=this.addChild(f));return 0<
a.length?g.findOrCreateNode(a):g};j.prototype.addCallback=function(b,c){b={eType:"eCallback",id:u++,name:c.name,fn:b,once:!!c.once,binding:c.binding,paused:!1};this.callbacks.push(b);return b};j.prototype.destroyCallbacks=function(b){var c=[],a,f,g,e=0;for(a=0;a<this.callbacks.length;a++){g=!1;for(f=0;f<b.length;f++)if(this.callbacks[a].id==b[f]){g=!0;++e;break}g||c.push(this.callbacks[a])}this.callbacks=c;return e};d.on=s;d.idle=function(b,c,a,f){function g(){i&&clearTimeout(i);i=void 0}function e(a){a&&
(m=a);g();i=setTimeout(d,m)}function d(){i=void 0;h.pause(!0);a.apply(l);l.pause()||(e(),h.pause(!1))}var i,h,j=!1,m=c,l={eType:"IdleEventListener",destroy:function(){g();h.destroy()},pause:function(a,b){if("undefined"===typeof a)return j;(j=a)?(g(),h.pause(!0)):i||(e(b),h.pause(!1))},start:function(a){this.pause(!1,a)},stop:function(){this.pause(!0)},touch:function(){h.emit()}};h=s(b,e,f);e();return l};d.once=function(b,c,a){a=a||{};a.once=!0;return s(b,c,a)};d.emit=w;d.collect=function(){w.apply(i,
[{collect:!0}].concat(Array.prototype.slice.call(arguments)))};d.connect=function(){var b=Array.prototype.slice.call(arguments),c=b.shift();return d.on(c,function(){for(var a=Array.prototype.slice.call(arguments),c=0;c<b.length;++c)if("string"===typeof b[c])d.emit.apply(i,[b[c]].concat(a));else if("function"===typeof b[c]&&b[c].eType===t)b[c](a[0])})};d.destroy=q;d.val=function(b){var c=m.findOrCreateNode(b,!1);"undefined"===typeof c.eValueObject&&(c.eValueObject={eType:"ValueObject",name:b,data:void 0,
initialized:!1,getterQueue:[],listener:[]},c.eValueFunction=function(a){var b=function(){return 0===arguments.length?c.eValueFunction.get():c.eValueFunction.set(arguments[0])};b.eType=t;b.eValueObject=a;b.set=function(b){a.data=b;if(!a.initialized){for(b=0;b<a.getterQueue.length;b++)try{a.getterQueue[b](a.data)}catch(c){l.error("e_val('"+a.name+"') getter error",c)}delete a.getterQueue;a.initialized=!0}for(b=0;b<a.listener.length;b++)try{a.listener[b](a.data)}catch(d){l.error("e_val('"+a.name+"') on[change] listener error",
d)}return a.data};b.on=function(b){a.listener.push(b);var e=x(a.name,p,c,{callback:b});return{eType:p,id:e,name:a.name,destroy:function(){d.destroy(e);delete this.eType;delete this.id;delete this.name;delete this.destroy}}};b.get=function(b){if("function"===typeof b)a.initialized?b(a.data):a.getterQueue.push(b);else return a.data};b.isEqual=function(b){return a.data===b};b.isDefined=function(){return a.initialized};return b}(c.eValueObject));return c.eValueFunction};d.get=function(b,c){d.val(b).get(c)};
d.set=function(b,c){d.val(b).set(c)};d.options={pathSeparator:"/",greedyChar:"*",insatiableSequence:"**",trace:!1,debug:!1};d._rootNode=m;d.log=l})();
