// custom_event.js
// ===============
//
// Created at 2010/05/07
// Copyright (c) 2010-2012 Wolfger Schramm <wolfger@spearwolf.de>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
(function(){function k(c,a){this.eType="EventNode";this.name=c;this.parentNode=a;this.children=[];this.greedyChildren=[];this.insatiableChildren=[];this.callbacks=[]}function r(c,a,b){b=b||{};b.name=c;var g=n.findOrCreateNode(c).addCallback(a,b);return{eType:"EventListener",id:g.id,name:g.name,destroy:function(){d.destroy(g.id);delete this.eType;delete this.id;delete this.name;delete this.destroy;delete this.emit;delete this.pause},emit:function(){d.emit.apply(j,[g.name].concat(Array.prototype.slice.call(arguments)))},
pause:function(b){"boolean"===typeof b&&(g.paused=b);return g.paused}}}function s(c,a){var b=[],g=[],f,e,o,l=c,h=a;(o="object"===typeof l)?"function"===typeof l.collect&&(f=l.collect):(h=c,l={});for(e=o?2:1,o=arguments.length;e<o;++e)!0===l.collect&&e===o-1&&"function"===typeof arguments[e]?f=arguments[e]:b.push(arguments[e]);m.traceGroup("_e.emit ->",h);var k;"object"!==typeof d._emitStackTrace?d._emitStackTrace={currentLevel:1,topicPath:[]}:++d._emitStackTrace.currentLevel;k=d._emitStackTrace;n.matchNodes(h,
function(a,c){try{var f=[],l=function(b){return function(){f.push(b)}},o=function(b){return function(){b.paused=!0}},j,p,i,n;for(e=0;e<a.callbacks.length;e++)i=a.callbacks[e],i.paused?m.trace("_e.on -> (paused)",i.name,"["+i.id+"]",i):0>k.topicPath.indexOf(i.id)?(k.topicPath.push(i.id),p=i.binding||{},p.name=h,p.destroy=l(i.id),"undefined"===typeof p.eType&&(p.eType="EventListener"),"function"!==typeof p.pause&&(p.pause=o(i)),n=b,"undefined"!==typeof c&&(p.pathArgs=c.split(d.options.pathSeparator),
n=p.pathArgs.concat(b)),m.trace("_e.on ->",i.name,"["+i.id+"]",i,"args=",n),j=i.fn.apply(p,n),i.once&&f.push(i.id),null!==j&&"undefined"!==typeof j&&g.push(j),k.topicPath.pop()):m.error("_e.on -> (skipped/recursion)",i.name,"["+i.id+"]",i);a.destroyCallbacks(f)}catch(q){m.error(q)}});--d._emitStackTrace.currentLevel;0===d._emitStackTrace.currentLevel&&(d._emitStackTrace={currentLevel:0,topicPath:[]});f&&0<g.length&&f.apply(j,g);m.traceGroupEnd()}function q(c,a){a=a||n;if("number"===typeof c){if(0<
a.destroyCallbacks([c]))return!0;var b;for(b=0;b<a.children.length;b++)if(q(c,a.children[b]))return!0;for(b=0;b<a.greedyChildren.length;b++)if(q(c,a.greedyChildren[b]))return!0;for(b=0;b<a.insatiableChildren.length;b++)if(q(c,a.insatiableChildren[b]))return!0;return!1}}function t(c,a){var c=c.replace(/\/+$/,""),b=[],g=[],f;m.debugGroup("_e.Module ->",c);"_init"in a&&(m.debug("constructor",c+d.options.pathSeparator+d.options.insatiableSequence),b.push(d.once(c+d.options.pathSeparator+d.options.insatiableSequence,
a._init,{binding:a})));for(var e in a)if(a.hasOwnProperty(e)&&(f=e.match(/^(on|module) (.+)$/)))"on"===f[1]&&"function"===typeof a[e]&&"_init"!==e&&(f=f[2].split(" "),1===f.length?(m.debug("on",c+d.options.pathSeparator+f[0]),b.push(d.on(c+d.options.pathSeparator+f[0],a[e],{binding:a}))):".."===f[1]&&(m.debug("on",c+d.options.pathSeparator+f[0]+d.options.pathSeparator+d.options.insatiableSequence),b.push(d.on(c+d.options.pathSeparator+f[0]+d.options.pathSeparator+d.options.insatiableSequence,a[e],
{binding:a})))),"module"===f[1]&&"object"===typeof a[e]&&g.push(t(c+d.options.pathSeparator+f[2],a[e]));m.debugGroupEnd();a.destroy=function(){var a;for(a=0;a<b.length;++a)b[a].destroy();for(a=0;a<g.length;++a)g[a].destroy()};var o=!1;a.pause=function(a){if("boolean"===typeof a){o=a;var c;for(c=0;c<b.length;++c)b[c].pause(a);for(c=0;c<g.length;++c)g[c].pause(a)}return o};a.eType="eModule";return a}var j=this,d={VERSION:"0.7.0-pre"};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&
(exports=module.exports=d),exports._e=d):"function"===typeof define&&define.amd?(define("custom_event",function(){return d}),define("custom_event/global",function(){return j._e=d})):j._e=d;var m=function(){var c="undefined"!==typeof j.console&&"function"===typeof Function&&"function"===typeof Function.prototype.bind,a=c&&"function"===typeof j.console.group,b={},g=!c?void 0:function(a){return Function.prototype.bind.call(console[a],console)},f=c?g("error"):null,e=c?g("log"):null,o=c?g("log"):null,
l=a?g("group"):null,h="";c?(b.error=function(){f.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},b.debug=function(){d.options.debug&&e.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},b.trace=function(){d.options.trace&&o.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},a?(b.debugGroup=function(){d.options.debug&&l.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},
b.debugGroupEnd=function(){d.options.debug&&console.groupEnd()},b.traceGroup=function(){d.options.trace&&l.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},b.traceGroupEnd=function(){d.options.trace&&console.groupEnd()}):(b.debugGroup=function(){d.options.debug&&(e.apply(j,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments))),h+="    ")},b.traceGroup=function(){d.options.trace&&(o.apply(j,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments))),
h+="    ")},b.traceGroupEnd=b.debugGroupEnd=function(){h=h.substr(0,h.length-4)})):b.error=b.debug=b.trace=b.traceGroup=b.traceGroupEnd=function(){};return b}(),n=new k,u=1;k.prototype.fullPathName=function(){return"undefined"===typeof this.name?d.options.pathSeparator:this._fullPathName()};k.prototype._fullPathName=function(){return"undefined"===typeof this.name?"":this.parentNode._fullPathName()+d.options.pathSeparator+this.name};k.prototype.addChild=function(c){var a=new k(c,this);c===d.options.greedyChar?
this.greedyChildren.push(a):c===d.options.insatiableSequence?this.insatiableChildren.push(a):this.children.push(a);return a};k.prototype.splitPath=function(c){for(var c=c.split(d.options.pathSeparator),a=null;null===a||0===a.length;)a=c.shift();if(a===d.options.insatiableSequence)return[a,""];for(var b=[],g=0;g<c.length&&!(b.push(c[g]),c[g]===d.options.insatiableSequence);g++);return[a,0===b.length?"":b.join(d.options.pathSeparator)]};k.prototype.matchNodes=function(c,a){var b=this.splitPath(c),g=
b[0],b=b[1],f=this,e;for(e=0;e<f.insatiableChildren.length;e++)a(f.insatiableChildren[e],c);if(0<b.length){for(e=0;e<this.children.length;e++)f=this.children[e],(g===d.options.greedyChar||g===f.name)&&f.matchNodes(b,a);for(e=0;e<this.greedyChildren.length;e++)this.greedyChildren[e].matchNodes(b,a)}else{for(e=0;e<this.children.length;e++)f=this.children[e],(g===d.options.greedyChar||g===f.name)&&a(f);for(e=0;e<this.greedyChildren.length;e++)a(this.greedyChildren[e])}};k.prototype.findOrCreateNode=
function(c){var a=this.splitPath(c),c=a[0],a=a[1],b=function(a){return function(b){var c,d;for(c=0;c<a.children.length;c++)if(d=a.children[c],b===d.name)return d;for(c=0;c<a.greedyChildren.length;c++)if(d=a.greedyChildren[c],b===d.name)return d;return null}}(this)(c);null===b&&(b=this.addChild(c));return 0<a.length?b.findOrCreateNode(a):b};k.prototype.addCallback=function(c,a){c={eType:"eCallback",id:u++,name:a.name,fn:c,once:!!a.once,binding:a.binding,paused:!1};this.callbacks.push(c);return c};
k.prototype.destroyCallbacks=function(c){var a=[],b,d,f,e=0;for(b=0;b<this.callbacks.length;b++){f=!1;for(d=0;d<c.length;d++)if(this.callbacks[b].id==c[d]){f=!0;++e;break}f||a.push(this.callbacks[b])}this.callbacks=a;return e};d.on=r;d.idle=function(c,a,b,d){function f(){l&&clearTimeout(l);l=void 0}function e(a){a&&(m=a);f();l=setTimeout(k,m)}function k(){l=void 0;h.pause(!0);b.apply(n);n.pause()||(e(),h.pause(!1))}var l,h,j=!1,m=a,n={eType:"IdleEventListener",destroy:function(){f();h.destroy()},
pause:function(a,b){if("undefined"===typeof a)return j;(j=a)?(f(),h.pause(!0)):l||(e(b),h.pause(!1))},start:function(a){this.pause(!1,a)},stop:function(){this.pause(!0)},touch:function(){h.emit()}};h=r(c,e,d);e();return n};d.once=function(c,a,b){b=b||{};b.once=!0;return r(c,a,b)};d.emit=s;d.collect=function(){s.apply(j,[{collect:!0}].concat(Array.prototype.slice.call(arguments)))};d.connect=function(){var c=Array.prototype.slice.call(arguments),a=c.shift();return d.on(a,function(){for(var a=Array.prototype.slice.call(arguments),
g=0;g<c.length;++g)d.emit.apply(j,[c[g]].concat(a))})};d.destroy=q;d.Module=t;d.options={pathSeparator:"/",greedyChar:"*",insatiableSequence:"**",trace:!1,debug:!1};d._rootNode=n;d.log=m})();
